apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  jwt-secret: "your-super-secret-jwt-key-change-this-in-production-min-32-chars"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  AUTH_SERVICE_URL: "http://auth-service:8000"
  PATIENT_SERVICE_URL: "http://patient-service:8001"
  DOCTOR_SERVICE_URL: "http://doctor-service:8002"
  APPOINTMENT_SERVICE_URL: "http://appointment-service:8003"
  MEDICAL_RECORDS_SERVICE_URL: "http://medical-records-service:8004"
  BILLING_SERVICE_URL: "http://billing-service:8006"
